### ISSUE TITLE
Create layout component with api context

### ISSUE THREAD

**Issue by mz106** [mz106/accountability-fe#4]
--src
  --components
    --context
      --userContext
    --layout
    --header
    --footer
    

Please branch from feature/state-management and create a userContext component, Layout component, Header Component and Footer component. 

Add dummy state for the time being to the user context. 

Please wrap the Layout in the UserContext and wrap App in appjs  with Layout component - please ensure that strict mode in still engaged. 

Please follow the following commit message format - "#<issue number as integer> <message here>"

**Comment by heydut** [comment]
Im not sure about this part "wrap the **about** in the UserContext" but everything is working.

**Comment by mz106** [comment]
> Im not sure about this part "wrap the **about** in the UserContext" but everything is working.

Layout, not about. I'll amend the issue - my bad on a typo. Thanks Dut.

**Comment by mz106** [comment]
Dut, I have approved pull request #4. Please merge when ready.
